fix annotaion to fix spinnaker deploy
infobloxopen/cert-manager pull request #4
Opened 2020-03-19 12:49 UTC by burov

By default spinnaker pipeline override annotations 

app.kubernetes.io/name and  app.kubernetes.io/managed-by set them to correct values.

This will allow us to deploy cert-manager using spinnaker

2020-03-21 23:54 UTC, drewwells requested changes
I believe .Release.Name is a requirement for spinnaker but Im not following what the other changes like .Release.Service are for. Can you link to a spinnaker build failure? A successful demo of these changes would be helpful too

Changes are made via git patch files. This makes it possible to pull in upstream changes then lay our changes on top of them. See 01-crds.yaml as an example. I made some make rules to simplify the creation.

```
// make changes, stage them
git add .
// create a patch, rename it to 03-{something}.patch
make makepatch
git add -A .
// commit results
```

2020-03-21 23:54 UTC, drewwells commented on stable/cert-manager/templates/cainjector-deployment.yaml
> +    app.kubernetes.io/name: {{ .Release.Name }}
This will collide with the primary deployment. They need to set a component label, but for now do this {{ .Release.Name }}-cainjector

2020-03-23 19:32 UTC, burov commented
Spinnaker error 

```
Exception ( Monitor Deploy )
Deploy failed: The Deployment “cert-manager-cainjector” is invalid: spec.template.metadata.labels: Invalid value: map[string]string{“app”:“cainjector”, “app.kubernetes.io/instance”:“cert-manager”, “app.kubernetes.io/managed-by”:“spinnaker”, “app.kubernetes.io/name”:“cainjector”, “helm.sh/chart”:“cert-manager-v0.13.1”}: selector does not match template labels
```

2020-03-23 19:46 UTC, drewwells approved these changes
LGTM

2020-03-23 19:46 UTC, merged